---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        client_id: '{{ .monitoring_grafana_oidc_client_id }}'
        client_secret: '{{ .monitoring_grafana_oidc_client_secret }}'

  dataFrom:
    - extract:
        key: monitoring
