---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  chartRef:
    kind: OCIRepository
    name: nvidia-device-plugin
  interval: 1h
  values:
    runtimeClassName: nvidia
    failOnInitError: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: extensions.talos.dev/nvidia-open-gpu-kernel-modules-production
                  operator: Exists
