config:
  bind: 0.0.0.0:25565
  onlineMode: true
  shouldPreventClientProxyConnections: true
  servers:
    minecraft: minecraft.games.svc.cluster.local:25565
    limbo: 127.0.0.1:30000
  try:
    - minecraft
    - limbo
  forwarding:
    mode: velocity
  status:
    motd: "xcd.dev"
    showMaxPlayers: 20
    favicon: ""
