---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gate-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        forwarding.secret: '{{ .minecraft_forwarding_secret }}'
  dataFrom:
    - extract:
        key: minecraft
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gate-allowlist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      metadata:
        annotations:
          reloader.stakater.com/ignore: 'true'
      data:
        minecraft: '{{ .minecraft_allowlist }}'
  dataFrom:
    - extract:
        key: minecraft
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .private_registry_credentials }}'
  dataFrom:
    - extract:
        key: shared
