---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - tank.internal
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  jobName: nfs_probe
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - tank.internal:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: slzb-icmp
spec:
  jobName: slzb_probe
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - slzb-06.internal
        - slzb-mr1.internal
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter
      action: replace
