---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        forwarding.secret: '{{ .minecraft_forwarding_secret }}'
  dataFrom:
    - extract:
        key: minecraft
