---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  interval: 1h
  values:
    fullnameOverride: victoria-logs-collector

    podMonitor:
      enabled: true

    remoteWrite:
      - url: http://victoria-logs.monitoring.svc.cluster.local:9428

    fileCollector:
      - glob: /var/run/cilium/hubble/traffic.log
        extraFields: '{"app":"hubble","kind":"traffic"}'
      - glob: /var/run/cilium/hubble/denied.log
        extraFields: '{"app":"hubble","kind":"denied"}'

    extraVolumes:
      - name: hubble-export
        hostPath:
          path: /var/run/cilium/hubble
          type: DirectoryOrCreate

    extraVolumeMounts:
      - name: hubble-export
        mountPath: /var/run/cilium/hubble
        readOnly: true

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
