---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        SEARXNG_SECRET: '{{ .searxng_secret_key }}'
        SEARXNG_VALKEY_URL: 'valkey://dragonfly.database.svc.cluster.local:6379/5'

  dataFrom:
    - extract:
        key: searxng
