---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-mcp-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        OUTLINE_MCP_TOKEN: 'Bearer {{ .mcps_outline_bearer_token }}'

  dataFrom:
    - extract:
        key: mcps
