---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smtp-relay
spec:
  chartRef:
    kind: OCIRepository
    name: smtp-relay
  interval: 1h
  values:
    controllers:
      smtp-relay:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: 'true'
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: smtp-relay
        containers:
          app:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.9.5
            env:
              SMTP_RELAY_HOSTNAME: smtp-relay.xcd.dev
              SMTP_RELAY_SERVER_PORT: 587
              SMTP_RELAY_SMTP_PORT: 25
              SMTP_RELAY_METRICS_PORT: 8080
            envFrom:
              - secretRef:
                  name: smtp-relay-secrets
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 64Mi

    service:
      app:
        type: ClusterIP
        ports:
          smtp:
            port: 25
          metrics:
            port: 8080

    persistence:
      cache:
        type: emptyDir
        medium: Memory
      config:
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
