---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-postgres
spec:
  refreshInterval: '0'
  target:
    template:
      metadata:
        labels:
          cnpg.io/reload: 'true'
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'database'
      data:
        username: ${DATABASE_OWNER:=${APP}}
        password: '{{ .password }}'
        host: ${DATABASE_HOST:=shared-pooler.database.svc}
        database: ${APP}
        url: 'postgresql://${DATABASE_OWNER:=${APP}}:{{ .password }}@${DATABASE_HOST:=shared-pooler.database.svc}:5432/${APP}?sslmode=disable'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
