---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        PG_BACKUP_ACCESS_KEY_ID: '{{ .authentik_nas_backup_access_key_id }}'
        PG_BACKUP_ACCESS_SECRET_KEY: '{{ .authentik_nas_backup_access_secret_key }}'
        pg_password: '{{ .authentik_pg_pwd }}'
        secret_key: '{{ .authentik_secret_key }}'

  dataFrom:
    - extract:
        key: authentik

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: '{{ .authentik_pg_pwd }}'
  dataFrom:
    - extract:
        key: authentik
