---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda-add-ons-http
spec:
  chartRef:
    kind: OCIRepository
    name: keda-add-ons-http
  interval: 1h
  values:
    interceptor:
      pdb:
        enabled: false
      readinessTimeout: 5m
      replicas:
        max: 1
        min: 1
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          memory: 128Mi
    operator:
      replicas: 1
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          memory: 128Mi
    scaler:
      replicas: 1
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          memory: 64Mi
