---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crawl4ai-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        CRAWL4AI_API_TOKEN: '{{ .crawl4ai_api_token }}'
  dataFrom:
    - extract:
        key: crawl4ai
