---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        UP_UNIFI_DEFAULT_API_KEY: '{{ .monitoring_unpoller_api_key }}'

  dataFrom:
    - extract:
        key: monitoring
