---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./mcpgroup.yaml
  - ./telemetry.yaml
  - ./vmcpserver.yaml
  - ./httproute.yaml
  - ./servicemonitor.yaml
  - ./prometheusrule.yaml
  - ./grafanadashboard.yaml
