---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        pod:
          terminationGracePeriodSeconds: 120
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: jellyfin
          securityContext:
            runAsNonRoot: true
            runAsUser: 5003
            runAsGroup: 3007
            fsGroup: 3007
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 104
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 12.1@sha256:008ec8024bdaaa6f0a3f0de468e185633eeba9d67c56936e8dbf5ef6b8d6200f
            env:
              - name: TZ
                value: Europe/Berlin
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  failureThreshold: 30
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 25m
                memory: 1Gi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: 8096

    route:
      app:
        hostnames:
          - 'watch.xcd.dev'
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      config:
        existingClaim: jellyfin
        advancedMounts:
          jellyfin:
            app:
              - path: /config

      media:
        type: nfs
        server: tank.internal
        path: /mnt/home-pool/library/media
        globalMounts:
          - path: /mnt/media

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
          - path: /cache
