---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        client-secret: '{{ .renovate_oauth_client_secret }}'

  dataFrom:
    - extract:
        key: renovate
