---
working_dir: ./docker/zeus
reconciliation:
  enabled: true
auto_discovery:
  enabled: true
  depth: 1
  delete: true
force_recreate: false
external_secrets:
  ZEUS_MONITORING_PASSWORD: 'op://zeus/monitoring/ingest_password'
