---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        CF_API_TOKEN: '{{ .cloudflare_dns_token }}'

  dataFrom:
    - extract:
        key: cloudflare
