---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: ${APP}
spec:
  source:
    fromPolicy:
      name: ${APP}
      offset: 0
  target:
    populator: {}
  policy:
    onMissingSnapshot: Continue
  mover:
    securityContext:
      runAsUser: ${KOPIUR_PUID:=1000}
      runAsGroup: ${KOPIUR_PGID:=1000}
    podSecurityContext:
      fsGroup: ${KOPIUR_PGID:=1000}
      fsGroupChangePolicy: OnRootMismatch
