---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-job-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        RENOVATE_TOKEN: '{{ .renovate_forgejo_bot_token }}'
        RENOVATE_GITHUB_COM_TOKEN: '{{ .renovate_github_com_token }}'
        RENOVATE_HOST_RULES: >-
          [{"hostType":"docker","matchHost":"reg.xcd.dev","username":"{{ .renovate_private_registry_username }}","password":"{{ .renovate_private_registry_password }}"}]
        RENOVATE_WEBHOOK_TOKEN: '{{ .renovate_webhook_token }}'

  dataFrom:
    - extract:
        key: renovate
