---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        WIREGUARD_PRIVATE_KEY: '{{ .qbittorrent_proton_private_key }}'

  dataFrom:
    - extract:
        key: qbittorrent
