---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        TOWONEL_INVITE_TOKEN: '{{ .towonel_invite_token }}'

  dataFrom:
    - extract:
        key: towonel
