---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        MEMINI_API_KEY: "{{ .memini_api_key }}"
        BIFROST_VK_MEMINI: "{{ .bifrost_vk_memini }}"
  dataFrom:
    - extract:
        key: memini
    - extract:
        key: bifrost
