containers:
  - name: main
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:175bb41fcb7d53a1316bc1288aa20f07d68f3394650177bdc88462bf87054036
    imagePullPolicy: IfNotPresent
    env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 4Gi
priorityClassName: batch-low
restartPolicy: Never
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
