---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-vmcp-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        OPENAI_API_KEY: '{{ .bifrost_vk_toolhive }}'
  dataFrom:
    - extract:
        key: bifrost
