---
- name: Bootstrap Zeus
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check host connectivity
      ansible.builtin.ping:

    - name: Read secrets from 1Password
      ansible.builtin.shell: "vals get 'ref+op://zeus/{{ item.key }}' < /dev/null"
      delegate_to: localhost
      become: false
      check_mode: false
      changed_when: false
      no_log: true
      loop:
        - key: doco-cd/credential
        - key: doco-cd/api_secret
      register: secrets_raw

    - name: Set secret facts
      ansible.builtin.set_fact:
        op_sa_token: '{{ secrets_raw.results[1].stdout }}'
        api_secret: '{{ secrets_raw.results[2].stdout }}'
      no_log: true

    - name: Create Zeus Docker network
      community.docker.docker_network:
        name: zeus
        driver: bridge
        state: present

    - name: doco-cd
      vars:
        dococd_config_dir: /opt/doco-cd
      block:
        - name: doco-cd | Create directory
          ansible.builtin.file:
            path: '{{ dococd_config_dir }}'
            state: directory
            owner: '{{ ansible_user }}'
            group: '{{ ansible_user }}'
            mode: '0700'

        - name: doco-cd | Copy docker-compose app file
          ansible.builtin.copy:
            src: ../../docker/zeus/.doco-cd/docker-compose.app.yaml
            dest: '{{ dococd_config_dir }}/docker-compose.yaml'
            owner: '{{ ansible_user }}'
            group: '{{ ansible_user }}'
            mode: '0644'
          register: compose_file

        - name: doco-cd | Create secrets
          ansible.builtin.copy:
            dest: '{{ dococd_config_dir }}/{{ item.name }}'
            content: |
              {{ item.content }}
            owner: '{{ ansible_user }}'
            group: '{{ ansible_user }}'
            mode: '0600'
          no_log: true
          loop:
            - name: 1pw_token
              content: '{{ op_sa_token }}'
            - name: api_secret
              content: '{{ api_secret }}'

        - name: doco-cd | Run docker-compose
          community.docker.docker_compose_v2:
            project_src: '{{ dococd_config_dir }}'
            files:
              - docker-compose.yaml
            pull: always
            state: present
          when: not ansible_check_mode

        - name: doco-cd | Wait for healthy
          community.docker.docker_container_info:
            name: doco-cd
          register: dococd_info
          until: dococd_info.container.State.Health.Status == "healthy"
          retries: 30
          delay: 10
          when: not ansible_check_mode
