---
name: custom/home-whitelist
description: "Whitelist home ISP (Telefonica Germany / O2 - AS6805) and VPS provider (Hetzner - AS24940)"
whitelist:
  reason: "home ISP (Telefonica Germany / O2) or Hetzner (VPS provider)"
  expression:
    - evt.Meta.ASNumber == "6805" || evt.Meta.ASNumber == "24940"
