---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        api_key: '{{ .prowlarr_api_key }}'

  dataFrom:
    - extract:
        key: prowlarr
