---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocharted
spec:
  chartRef:
    kind: OCIRepository
    name: ocharted
  interval: 1h
  values:
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
      hostnames:
        - 'ocharted.xcd.dev'
    monitoring:
      serviceMonitor:
        enabled: true
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: ocharted
    resources:
      requests:
        cpu: 10m
      limits:
        memory: 512Mi
