---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        N8N_ENCRYPTION_KEY: '{{ .n8n_encryption_key }}'
        N8N_RUNNERS_AUTH_TOKEN: '{{ .n8n_runners_auth_token }}'

  dataFrom:
    - extract:
        key: n8n
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .private_registry_credentials }}'

  dataFrom:
    - extract:
        key: shared
