---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        GITHUB_MCP_TOKEN: 'Bearer {{ .mcps_github_token }}'

  dataFrom:
    - extract:
        key: mcps
