alerting:
  pushover:
    application-token: ${PUSHOVER_TOKEN}
    user-key: ${PUSHOVER_USER_KEY}
    title: Gatus
    priority: 1
    resolved-priority: 0
    default-alert:
      description: health-check failed
      failure-threshold: 3
      send-on-resolved: true
      success-threshold: 2

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - '[CONNECTED] == true'

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - '[CONNECTED] == true'

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - '[CONNECTED] == true'

metrics: true

storage:
  type: postgres
  path: ${POSTGRES_URL}
  caching: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/44176694
  link: https://github.com/gabrielcosi
  buttons:
    - name: Github
      link: https://github.com/gabrielcosi

web:
  port: ${GATUS_WEB_PORT}
