---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        OAUTH2_CLIENT_ID: '{{ .miniflux_oauth_client_id }}'
        OAUTH2_CLIENT_SECRET: '{{ .miniflux_oauth_client_secret }}'
  dataFrom:
    - extract:
        key: miniflux
