---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .private_registry_credentials }}'

  dataFrom:
    - extract:
        key: shared
