---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freeze-frame
spec:
  chartRef:
    kind: OCIRepository
    name: freeze-frame
  interval: 1h
  values:
    controllers:
      freeze-frame:
        pod:
          imagePullSecrets:
            - name: registry-credentials
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

        containers:
          app:
            image:
              repository: reg.xcd.dev/private/freeze-frame
              tag: latest@sha256:20a53e028e1b27b1f5afbc4827a64e783d0ec56814837faad6ae6f768ae9ad1f
            resources:
              requests:
                cpu: 1m
                memory: 10Mi
              limits:
                memory: 10Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ['ALL']

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
          - path: /var/run
          - path: /tmp

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - 'freeze-frame.xcd.dev'
        parentRefs:
          - name: envoy-internal
            namespace: network
