---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freeze-frame
spec:
  chartRef:
    kind: OCIRepository
    name: freeze-frame
  interval: 1h
  values:
    controllers:
      freeze-frame:
        pod:
          imagePullSecrets:
            - name: registry-credentials
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

        containers:
          app:
            image:
              repository: registry.xcd.dev/gabrielcosi/freeze-frame
              tag: latest@sha256:800b2558971731b353cc0491fa38bcbed7f0cc006786386ee7af674fb5ed062b
            resources:
              requests:
                cpu: 1m
                memory: 32Mi
              limits:
                memory: 32Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ['ALL']

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
          - path: /var/run
          - path: /tmp

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - 'freeze-frame.xcd.dev'
        parentRefs:
          - name: envoy-internal
            namespace: network
