---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gabrielcosi-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        DRAGONFLY_PASSWORD: '{{ .portfolio_dragonfly_pwd }}'
        AWS_ACCESS_KEY_ID: '{{ .portfolio_backup_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ .portfolio_backup_access_secret_key }}'
        REDIS_URL: 'redis://:{{ .portfolio_dragonfly_pwd }}@gabrielcosi-dragonfly.portfolio.svc.cluster.local'

  dataFrom:
    - extract:
        key: portfolio

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .private_registry_credentials }}'

  dataFrom:
    - extract:
        key: shared
