---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gabrielcosi
spec:
  chartRef:
    kind: OCIRepository
    name: gabrielcosi
  interval: 1h
  values:
    controllers:
      gabrielcosi:
        replicas: 2
        strategy: RollingUpdate
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: gabrielcosi
          imagePullSecrets:
            - name: registry-credentials
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

        containers:
          app:
            image:
              repository: reg.xcd.dev/private/gabrielcosi.dev
              tag: latest@sha256:e9e38d49d4f873fae4cc13c89085d5c45423d3f05882d3ce049b7fe6088a8792
            envFrom:
              - secretRef:
                  name: gabrielcosi-secrets
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ['ALL']
            resources:
              requests:
                cpu: '5m'
                memory: '200Mi'
              limits:
                memory: '200Mi'

    service:
      app:
        ports:
          web:
            port: 3000

    route:
      app:
        hostnames:
          - 'gabrielcosi.dev'
        parentRefs:
          - name: envoy-external
            namespace: network
