---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        QUI__OIDC_CLIENT_ID: '{{ .qui_oidc_client_id }}'
        QUI__OIDC_CLIENT_SECRET: '{{ .qui_oidc_client_secret }}'
        QUI__SESSION_SECRET: '{{ .qui_session_secret }}'

  dataFrom:
    - extract:
        key: qui
