---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plik-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        PLIKD_OIDC_CLIENT_ID: '{{ .plik_oidc_client_id }}'
        PLIKD_OIDC_CLIENT_SECRET: '{{ .plik_oidc_client_secret }}'
  dataFrom:
    - extract:
        key: plik
