---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee-secrets
    template:
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: '{{ .zigbee_channel }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: '{{ .zigbee_network_key }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: '{{ .zigbee_pan_id }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: '{{ .zigbee_ext_pan_id }}'
        ZIGBEE2MQTT_CONFIG_MQTT_USER: '{{ .zigbee_mqtt_user }}'
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: '{{ .zigbee_mqtt_password }}'

  dataFrom:
    - extract:
        key: zigbee
