---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  chartRef:
    kind: OCIRepository
    name: spegel
  interval: 1h
  values:
    serviceMonitor:
      enabled: true

    service:
      registry:
        hostPort: 29999

    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    grafanaDashboard:
      enabled: true
      mode: GrafanaOperator
      grafanaOperator:
        allowCrossNamespaceImport: true
        matchLabels:
          dashboards: grafana
