---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        CLOUDFLARE_API_TOKEN: '{{ .cert_manager_cloudflare_api_token }}'

  dataFrom:
    - extract:
        key: cert-manager
