---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        PG_BACKUP_ACCESS_KEY_ID: '{{ .forgejo_nas_backup_access_key_id }}'
        PG_BACKUP_ACCESS_SECRET_KEY: '{{ .forgejo_nas_backup_access_secret_key }}'
        dragonfly_auth: '{{ .forgejo_dragonfly_pwd }}'

  dataFrom:
    - extract:
        key: forgejo

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        cache: |
          HOST=redis://:{{ .forgejo_dragonfly_pwd }}@forgejo-dragonfly.tools.svc.cluster.local:6379/0
        queue: |
          CONN_STR=redis://:{{ .forgejo_dragonfly_pwd }}@forgejo-dragonfly.tools.svc.cluster.local:6379/0
        session: |
          PROVIDER_CONFIG=redis://:{{ .forgejo_dragonfly_pwd }}@forgejo-dragonfly.tools.svc.cluster.local:6379/0
  dataFrom:
    - extract:
        key: forgejo

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-signing-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        ed25519: |
          {{ .forgejo_signing_private_key }}
        ed25519.pub: |
          {{ .forgejo_signing_public_key }}

  dataFrom:
    - extract:
        key: forgejo

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        key: '{{ .forgejo_oauth_client_id }}'
        secret: '{{ .forgejo_oauth_client_secret }}'

  dataFrom:
    - extract:
        key: forgejo

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-pg-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      type: kubernetes.io/basic-auth
      data:
        username: forgejo
        password: '{{ .forgejo_pg_pwd }}'
  dataFrom:
    - extract:
        key: forgejo
