---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-pg
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 3
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4587df73024408f5b2be9b4dd6ba2ccee8c9e5dc0c9a87c274c292291cc8a68c

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          cnpg.io/cluster: harbor-pg

  bootstrap:
    recovery:
      source: &src source
      database: harbor
      owner: harbor
      secret:
        name: harbor-pg-credentials

  externalClusters:
    - name: *src
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: harbor-store
          serverName: harbor-pg-v18

  storage:
    pvcTemplate:
      storageClassName: ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi

  resources:
    requests:
      memory: '256Mi'
      cpu: '50m'
    limits:
      memory: '512Mi'

  postgresql:
    parameters:
      timezone: Europe/Berlin
      max_wal_size: '512MB'
      min_wal_size: '128MB'
      max_slot_wal_keep_size: '1GB'
      wal_compression: 'on'
      wal_keep_size: '0'

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: harbor-store
        serverName: harbor-pg-v18

  managed:
    roles:
      - name: harbor
        ensure: present
        login: true
        passwordSecret:
          name: harbor-pg-credentials
