---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: harbor-dragonfly
spec:
  replicas: 2

  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi

  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=1
    - --cluster_mode=emulated

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: harbor-dragonfly
