---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-clusters
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-poolers
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: cnpg.io/poolerName
        operator: Exists
  podMetricsEndpoints:
    - port: metrics
