---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        OPENAI_API_KEY: '{{ .bifrost_vk_hermes }}'
        TELEGRAM_BOT_TOKEN: '{{ .hermes_telegram_bot_token }}'
        API_SERVER_KEY: '{{ .hermes_api_server_key }}'
        MEMINI_API_KEY: '{{ .memini_api_key }}'
        GITHUB_TOKEN: '{{ .hermes_github_token }}'
        CRAWL4AI_TOKEN: '{{ .crawl4ai_api_token }}'

  dataFrom:
    - extract:
        key: hermes
    - extract:
        key: bifrost
    - extract:
        key: memini
    - extract:
        key: crawl4ai
