---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        # Paperless
        PAPERLESS_SECRET_KEY: '{{ .paperless_ngx_secret_key }}'
        PAPERLESS_REDIS: redis://dragonfly.database.svc.cluster.local:6379/3
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "SCOPE": ["openid", "profile", "email", "groups"],
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "{{ .paperless_ngx_client_id }}",
                  "secret": "{{ .paperless_ngx_client_secret }}",
                  "settings": {
                    "server_url": "https://auth.xcd.dev/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ]
            }
          }

  dataFrom:
    - extract:
        key: paperless-ngx
