[SERVICE]
    Flush                     5
    Log_Level                 warn
    Parsers_File              /fluent-bit/etc/parsers.conf
    Storage.Path              /fluent-bit/data/storage
    Storage.Sync              normal
    Storage.Checksum          off
    Storage.Backlog.Mem_Limit 16M

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Path_Key          container_path
    Parser            docker
    Tag               docker.*
    Docker_Mode       on
    Docker_Mode_Flush 5
    DB                /fluent-bit/data/tail.db
    Skip_Empty_Lines  on
    Refresh_Interval  10
    Storage.Type      filesystem

[FILTER]
    Name   lua
    Match  docker.*
    Script /fluent-bit/etc/enrich.lua
    Call   enrich

[FILTER]
    Name    grep
    Match   docker.*
    Exclude container_name ^fluent-bit$

[OUTPUT]
    Name                 http
    Match                docker.*
    Host                 towonel-hub
    Port                 18429
    URI                  /insert/jsonline?_stream_fields=stream,container_name,host&_msg_field=log&_time_field=date
    Format               json_lines
    Json_Date_Format     iso8601
    Compress             gzip
    HTTP_User            vps
    HTTP_Passwd          ${VPS_MONITORING_PASSWORD}
    Log_Response_Payload false
    Storage.Total_Limit_Size 4G
