---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPRemoteProxy
metadata:
  name: context7-mcp
spec:
  remoteUrl: https://mcp.context7.com/mcp
  transport: streamable-http
  groupRef:
    name: mcp-tools
  telemetryConfigRef:
    name: prometheus
    serviceName: context7-mcp
  headerForward:
    addHeadersFromSecret:
      - headerName: CONTEXT7_API_KEY
        valueSecretRef:
          name: context7-mcp-token
          key: CONTEXT7_API_KEY
