apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        encryption-key: '{{ .bifrost_encryption_key }}'
        # upstream providers
        LLAMA_SWAP_API_KEY: '{{ .llama_swap_api_key }}'
        OPENCODE_API_KEY: '{{ .bifrost_opencode_api_key }}'
        TEXT_EMBEDDINGS_API_KEY: dummy
        # vks
        BIFROST_VK_MEMINI: '{{ .bifrost_vk_memini }}'
        BIFROST_VK_HERMES: '{{ .bifrost_vk_hermes }}'
        BIFROST_VK_OPENWEBUI: '{{ .bifrost_vk_openwebui }}'
        BIFROST_VK_TOOLHIVE: '{{ .bifrost_vk_toolhive }}'
        BIFROST_VK_N8N: '{{ .bifrost_vk_n8n }}'
        BIFROST_VK_PR_REVIEWER: '{{ .bifrost_vk_pr_reviewer }}'

  dataFrom:
    - extract:
        key: bifrost
    - extract:
        key: llama-swap
