---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./netpol.yaml
  - ./ocirepository.yaml
  - ./pdb.yaml
  - ./prometheusrule.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: bifrost-pricing
    files:
      - pricing.json=config/pricing.json
      - models.json=config/models.json
    literals:
      - "mcp-library.json={}"
  - name: bifrost-values
    files:
      - providers.yaml=config/providers.yaml
      - governance.yaml=config/governance.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
