---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cachette-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        CACHETTE_BOOTSTRAP_ADMIN_USER: '{{ .cachette_admin_user }}'
        CACHETTE_BOOTSTRAP_ADMIN_PASSWORD: '{{ .cachette_admin_password }}'
        CACHETTE_OIDC_CLIENT_ID: '{{ .cachette_oidc_client_id }}'
        CACHETTE_OIDC_CLIENT_SECRET: '{{ .cachette_oidc_client_secret }}'
  dataFrom:
    - extract:
        key: cachette
