---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      metadata:
        labels:
          cnpg.io/reload: 'true'
      data:
        PG_BACKUP_ACCESS_KEY_ID: '{{ .cnpg_nas_backup_access_key_id }}'
        PG_BACKUP_ACCESS_SECRET_KEY: '{{ .cnpg_nas_backup_access_secret_key }}'
  dataFrom:
    - extract:
        key: cnpg
