---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        token: '{{ .forgejo_runner_token }}'
        uuid: '{{ .forgejo_runner_uuid }}'

  dataFrom:
    - extract:
        key: forgejo
