---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        connections.yaml: |
          server:
            connections:
              user:
                url: http://forgejo-http.tools.svc.cluster.local:3000
                uuid: "{{ .forgejo_runner_uuid }}"
                token: "{{ .forgejo_runner_token }}"
              xcd:
                url: http://forgejo-http.tools.svc.cluster.local:3000
                uuid: "{{ .forgejo_runner_org_uuid }}"
                token: "{{ .forgejo_runner_org_token }}"

  dataFrom:
    - extract:
        key: forgejo
