---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dcgm-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.8.4
  url: oci://registry.xcd.dev/x/nvidia.github.io/dcgm-exporter/helm-charts/dcgm-exporter
