---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wyoming-openai-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        STT_OPENAI_KEY: '{{ .bifrost_vk_wyoming }}'
        TTS_OPENAI_KEY: '{{ .bifrost_vk_wyoming }}'

  dataFrom:
    - extract:
        key: bifrost
