---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        # App secrets
        SECRET_KEY: '{{ .outline_secret_key }}'
        UTILS_SECRET: '{{ .outline_utils_secret }}'
        # Redis
        REDIS_URL: 'redis://dragonfly.database.svc.cluster.local:6379/4'
        # OIDC
        OIDC_CLIENT_ID: '{{ .outline_oidc_client_id }}'
        OIDC_CLIENT_SECRET: '{{ .outline_oidc_client_secret }}'

  dataFrom:
    - extract:
        key: outline
