---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-gabrielcosi
  namespace: network
spec:
  dnsNames:
    - '*.gabrielcosi.dev'
    - 'gabrielcosi.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: cert-gabrielcosi
  usages:
    - digital signature
    - key encipherment
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-xcd
  namespace: network
spec:
  dnsNames:
    - '*.xcd.dev'
    - 'xcd.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: cert-xcd
  usages:
    - digital signature
    - key encipherment
