---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-secrets
    template:
      data:
        KONFLATE_TOKEN: '{{ .konflate_token }}'
        KONFLATE_WEBHOOK_SECRET: '{{ .konflate_webhook_secret }}'
        KONFLATE_WRITE_TOKEN: '{{ .renovate_forgejo_bot_token }}'
  dataFrom:
    - extract:
        key: konflate
    - extract:
        key: renovate
