---
name: monitoring

services:
  vmagent:
    image: quay.io/victoriametrics/vmagent:v1.148.0
    container_name: vmagent
    command:
      - --promscrape.config=/etc/vmagent/scrape.yaml
      - --remoteWrite.url=https://metrics.xcd.dev/api/v1/write
      - --remoteWrite.basicAuth.username=zeus
      - --remoteWrite.basicAuth.password=${ZEUS_MONITORING_PASSWORD}
      - --remoteWrite.label=cluster=homelab
      - --remoteWrite.label=machine=zeus
      - --remoteWrite.tmpDataPath=/vmagentdata
      - --remoteWrite.maxDiskUsagePerURL=1GB
    ports:
      - '8429:8429'
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    volumes:
      - ./vmagent.yaml:/etc/vmagent/scrape.yaml:ro
      - vmagentdata:/vmagentdata
    networks:
      - zeus

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.12.1
    container_name: node-exporter
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/containerd/.+|var/lib/kubelet/.+)($|/)
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    volumes:
      - /:/host:ro,rslave
    networks:
      - zeus

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:4.8.3
    container_name: dcgm-exporter
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - zeus

volumes:
  vmagentdata:

networks:
  zeus:
    external: true
