---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        client_id: '{{ .tailscale_oauth_client_id }}'
        client_secret: '{{ .tailscale_oauth_client_secret }}'
  dataFrom:
    - extract:
        key: tailscale
