---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaski
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: chaski-secret
    template:
      data:
        PUSHOVER_USER_KEY: "{{ .chaski_pushover_user_key }}"
        RADARR_PUSHOVER_TOKEN: "{{ .chaski_radarr_pushover_token }}"
        SONARR_PUSHOVER_TOKEN: "{{ .chaski_sonarr_pushover_token }}"
  dataFrom:
    - extract:
        key: chaski
