---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  interval: 1h
  values:
    ceph-csi-operator:
      controllerManager:
        manager:
          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: null
              memory: 192Mi
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
