---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-swap-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        LS_API_KEY: "{{ .llama_swap_api_key }}"
  dataFrom:
    - extract:
        key: llama-swap
