---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        PUSHOVER_TOKEN: '{{ .monitoring_gatus_pushover_token }}'
        PUSHOVER_USER_KEY: '{{ .monitoring_pushover_user_key }}'

  dataFrom:
    - extract:
        key: monitoring
