---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        HOMEASSISTANT_TOKEN: "{{ .mcps_ha_token }}"

  dataFrom:
    - extract:
        key: mcps
