---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: external-secrets
spec:
  groups:
    - name: external-secrets.rules
      rules:
        - alert: ExternalSecretsOperatorAbsent
          expr: |-
            absent(up{job=~"external-secrets.*"})
          for: 5m
          annotations:
            summary: >-
              External Secrets Operator has disappeared from Prometheus service discovery
          labels:
            severity: critical

        - alert: ExternalSecretNotReady
          expr: |-
            max by (namespace, name) (
              externalsecret_status_condition{type="Ready",status=~"[Ff]alse"} == 1
            )
          for: 10m
          annotations:
            summary: >-
              ExternalSecret {{ $labels.namespace }}/{{ $labels.name }} is not Ready
          labels:
            severity: warning

        - alert: ClusterSecretStoreNotReady
          expr: |-
            max by (name) (
              clustersecretstore_status_condition{type="Ready",status=~"[Ff]alse"} == 1
            )
          for: 10m
          annotations:
            summary: >-
              ClusterSecretStore {{ $labels.name }} is not Ready
          labels:
            severity: critical
