---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: text-embeddings
spec:
  dependsOn:
    - name: miroir
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/ai/text-embeddings/minilm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: text-embeddings-qwen3
spec:
  dependsOn:
    - name: miroir
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/ai/text-embeddings/qwen3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: text-embeddings-arctic
spec:
  dependsOn:
    - name: miroir
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/ai/text-embeddings/arctic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: text-embeddings-nomic
spec:
  dependsOn:
    - name: miroir
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/ai/text-embeddings/nomic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: text-embeddings-gemma
spec:
  dependsOn:
    - name: miroir
      namespace: miroir-system
  interval: 1h
  path: ./kubernetes/apps/ai/text-embeddings/gemma
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
