---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    template:
      data:
        OPENAI_API_KEY: '{{ .bifrost_vk_openwebui }}'
        AUDIO_STT_OPENAI_API_KEY: '{{ .bifrost_vk_openwebui }}'
        AUDIO_TTS_OPENAI_API_KEY: '{{ .bifrost_vk_openwebui }}'
        RAG_OPENAI_API_KEY: '{{ .bifrost_vk_openwebui }}'
        WEBUI_SECRET_KEY: '{{ .open_webui_secrey_key }}'
        OAUTH_CLIENT_ID: '{{ .open_webui_oauth_client_id }}'
        OAUTH_CLIENT_SECRET: '{{ .open_webui_oauth_client_secret }}'

  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: bifrost
