---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/flux-alerts
resources:
  - ./namespace.yaml
  - ./tailscale/operator/ks.yaml
  - ./tailscale/connectors/ks.yaml
  - ./external-dns/ks.yaml
  - ./towonel-agent/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./echo/ks.yaml
